### ISSUE TITLE
Snorby setup fails on Ubuntu 16.04 Xenial

### ISSUE THREAD

**Issue by 3ruce** [dustinmhorvath/OneStopIDS#1]
Or is it a case of diving in to see?

**Comment by dustinmhorvath** [comment]
I'm doing a test install now that actually failed. There's a patch in the
works that someone has submitted to the Snorby team as a pull request, and
if it works when applied manually I'll likely get it pushed into my script
as a handled exception. Probably get it pushed up sometime tomorrow.

**Comment by dustinmhorvath** [comment]
Test run on 16.04 Xenial fails during Snorby setup. This seems to be a known issue with changes to MySQL syntax in the version shipped with Xenial, and is an open issue with Snorby [here](https://github.com/Snorby/snorby/issues/428). A patch seems to be in the pull request stage with Snorby, and if it tests ok on here I'll roll it into a push within the next day or two as an exception.

**Comment by dustinmhorvath** [comment]
The patch in question _does_ seem to fix the issue with the Snorby:setup command execution. This issue will remain open pending further issues and patch inclusion in 'master'.

**Comment by 3ruce** [comment]
ok - good to know...
